# Generated by Django 5.1.7 on 2025-03-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterviewSession',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='question',
            name='is_project_related',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
