# Generated by Django 5.1.7 on 2025-03-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_delete_interviewsession_remove_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, default='skill', max_length=100, null=True),
        ),
    ]
